/* -*- mode: IDL; c-basic-offset: 4; indent-tabs-mode: nil; -*- */

#include "nsISupports.idl"
#include "nsIPropertyBag2.idl"

#include "compzillaIWindowObserver.idl"


[scriptable, uuid(95aa8ead-40a9-41c6-a643-e3dd531e0afd)]
interface compzillaIWindow : nsISupports
{
    void AddContentNode (in nsISupports content);
    void RemoveContentNode (in nsISupports content);

    void addObserver (in compzillaIWindowObserver observer);
    void removeObserver (in compzillaIWindowObserver observer);

    readonly attribute long nativeWindowId;

    // window property accessor
    nsIPropertyBag2 GetProperty (in PRUint32 prop);
};


%{ C++
#define COMPZILLA_WINDOW_CID \
  { 0x95aa8ead, 0x40a9, 0x41c6, \
      { 0xa6, 0x43, 0xe3, 0xdd, 0x53, 0x1e, 0x0a, 0xfd } }
#define COMPZILLA_WINDOW_CONTRACTID "@pyrodesktop.org/compzillaWindow"
%}
