/* -*- mode: IDL; c-basic-offset: 4; indent-tabs-mode: nil; -*- */

#include "nsISupports.idl"
#include "nsIDOMEvent.idl"
#include "compzillaIWindow.idl"
#include "nsIPropertyBag2.idl"


[scriptable, uuid(6797a12f-37a3-4ef4-8744-5bef35474240)]
interface compzillaIWindowEvent : nsIDOMEvent
{
    readonly attribute compzillaIWindow window;
};


[scriptable, uuid(620e5545-81d8-4393-8e8b-b835d128bdf8)]
interface compzillaIWindowConfigureEvent : compzillaIWindowEvent
{
    readonly attribute boolean mapped;
    readonly attribute boolean overrideRedirect;

    readonly attribute long x;
    readonly attribute long y;
    readonly attribute long width;
    readonly attribute long height;
    readonly attribute long borderWidth;

    readonly attribute compzillaIWindow aboveWindow;
};


[scriptable, uuid(a20d8a3f-b619-47db-8625-4a36e680e545)]
interface compzillaIWindowPropertyEvent : compzillaIWindowEvent
{
    readonly attribute long atom;
    readonly attribute boolean deleted;
    readonly attribute nsIPropertyBag2 value;
};
