/* -*- mode: IDL; c-basic-offset: 4; indent-tabs-mode: nil; -*- */
#include "nsISupports.idl"


[scriptable, uuid(1b3391c9-5ff0-42ca-8356-b4334f3a0424)]
interface compzillaIRenderingContext : nsISupports
{
};


%{ C++
//1b3391c9-5ff0-42ca-8356-b4334f3a0424
#define COMPZILLA_RENDERING_CONTEXT_CID \
  { 0x1b3391c9, 0x5ff0, 0x42ca, \
      { 0x83, 0x56, 0xb4, 0x33, 0x4f, 0x3a, 0x04, 0x24 } }
#define COMPZILLA_RENDERING_CONTEXT_CONTRACTID "@mozilla.org/content/canvas-rendering-context;1?id=compzilla"
%}

