/* -*- mode: IDL; c-basic-offset: 4; indent-tabs-mode: nil; -*- */
#include "nsISupports.idl"
#include "nsIDOMWindow.idl"
#include "compzillaIWindowManager.idl"


[scriptable, uuid(8bf6de0a-ed8f-47af-8757-41551542d196)]
interface compzillaIControl : nsISupports
{
    void RegisterWindowManager (in nsIDOMWindow window, in compzillaIWindowManager wm);

    // @property is just an atom name, which is ascii.
    PRUint32 InternAtom (in string property);

    void SendConfigureNotify (in PRUint32 xid, 
                              in PRUint32 x, in PRUint32 y, 
                              in PRUint32 width, in PRUint32 height, 
                              in PRUint32 border);
    void ConfigureWindow (in PRUint32 xid, 
                          in PRUint32 x, in PRUint32 y, 
                          in PRUint32 width, in PRUint32 height, 
                          in PRUint32 border);
};


%{ C++
#define COMPZILLA_CONTROL_CID \
  { 0xfb192a55, 0xb1de, 0x4b23, \
      { 0xa5, 0xb2, 0xa5, 0xad, 0xf8, 0xa4, 0xe4, 0x46 } }
#define COMPZILLA_CONTROL_CONTRACTID "@beatniksoftware.com/compzillaService"
%}
