/* -*- mode: IDL; c-basic-offset: 4; indent-tabs-mode: nil; -*- */
#include "nsISupports.idl"

// methods loaded on extension startup, global to the firefox process
[scriptable, uuid(0f3ab8b9-2350-408b-9465-13f4ef5466a1)]
interface compzillaIExtension : nsISupports 
{
};


%{ C++
/* b3255c2c-0222-4d6b-ac38-14390ab14ec2 */
#define COMPZILLA_EXTENSION_CID                                 \
        { 0xb3255c2c, 0x0222, 0x4d6b,                           \
          { 0xac, 0x38, 0x14, 0x39, 0x0a, 0xb1, 0x4e, 0xc2 } }
#define COMPZILLA_EXTENSION_CONTRACTID "@beatniksoftware.com/compzillaExtension"
%}

