/* -*- mode: IDL; c-basic-offset: 4; indent-tabs-mode: nil; -*- */
#include "nsISupports.idl"
#include "nsIDOMHTMLCanvasElement.idl"

[scriptable, uuid(4fa17c67-d131-4c96-a197-15f2ae1dd561)]
interface compzillaIRenderingContext : nsISupports
{
  readonly attribute nsIDOMHTMLCanvasElement canvas;

  void copyImageDataFrom (in PRUint32 drawable,
                          in PRInt32 src_x, in PRInt32 src_y,
                          in PRInt32 dest_x, in PRInt32 dest_y,
                          in PRUint32 w, in PRUint32 h);
};

%{ C++
//1b3391c9-5ff0-42ca-8356-b4334f3a0424
#define COMPZILLA_CANVASRENDERINGCONTEXT_CID \
  { 0x1b3391c9, 0x5ff0, 0x42ca, \
      { 0x83, 0x56, 0xb4, 0x33, 0x4f, 0x3a, 0x04, 0x24 } }
#define COMPZILLA_CANVASRENDERINGCONTEXT_CONTRACTID "@mozilla.org/content/canvas-rendering-context;1?id=compzilla"
%}

