/* -*- mode: IDL; c-basic-offset: 4; indent-tabs-mode: nil; -*- */
#include "nsISupports.idl"
#include "nsIDOMWindow.idl"
#include "nsIDOMEventTarget.idl"

[scriptable, uuid(38054e08-223b-4eea-adcf-442c58945704)]
interface compzillaIWindowManager : nsISupports
{
  void WindowCreated (in long xid);
  void WindowDestroyed (in long xid);

  void WindowMapped (in long xid);
  void WindowUnmapped (in long xid);

  void WindowConfigured (in long xid);
};
