/* -*- mode: IDL; c-basic-offset: 4; indent-tabs-mode: nil; -*- */

#include "nsISupports.idl"
#include "nsIDOMEvent.idl"


[scriptable, uuid(6797a12f-37a3-4ef4-8744-5bef35474240)]
interface compzillaIWindowEvent : nsIDOMEvent
{
    readonly attribute nsISupports window;
};


%{ C++
#define COMPZILLA_WINDOW_EVENT_CID \
  { 0x6797a12f, 0x37a3, 0x4ef4, \
      { 0x87, 0x44, 0x5b, 0xef, 0x35, 0x47, 0x42, 0x40 } }
#define COMPZILLA_WINDOW_EVENT_CONTRACTID "@pyrodesktop.com/compzillaWindowEvent"
%}


[scriptable, uuid(620e5545-81d8-4393-8e8b-b835d128bdf8)]
interface compzillaIWindowConfigureEvent : compzillaIWindowEvent
{
    readonly attribute boolean mapped;
    readonly attribute boolean overrideRedirect;

    readonly attribute long x;
    readonly attribute long y;
    readonly attribute long width;
    readonly attribute long height;
    readonly attribute long borderWidth;

    readonly attribute nsISupports aboveWindow;
};


[scriptable, uuid(a20d8a3f-b619-47db-8625-4a36e680e545)]
interface compzillaIWindowPropertyEvent : compzillaIWindowEvent
{
    readonly attribute long atom;
    readonly attribute boolean deleted;
};

[scriptable, uuid(cc0c1b9e-9d89-4800-94ce-89d47d17b976)]
interface compzillaIWindowClientMessageEvent : compzillaIWindowEvent
{
    readonly attribute long messageType;
    readonly attribute long format;
    readonly attribute long d1;
    readonly attribute long d2;
    readonly attribute long d3;
    readonly attribute long d4;
    readonly attribute long d5;
};
