/* -*- mode: IDL; c-basic-offset: 4; indent-tabs-mode: nil; -*- */

#include "nsISupports.idl"


[scriptable, uuid(8b482631-d5fe-4cba-9d5a-76023cce8d9c)]
interface compzillaIWindowObserver : nsISupports
{
    void destroy ();
    void map (in boolean overrideRedirect);
    void unmap ();

    void configure (in boolean mapped,
                    in boolean overrideRedirect,
                    in long x,
                    in long y,
                    in long width,
                    in long height,
                    in long borderWidth,
                    in nsISupports aboveWindow);

    void propertyChange (in long atom, in boolean deleted);

    void clientMessageRecv (in long messageType,
                            in long format,
                            in long d1,
                            in long d2,
                            in long d3,
                            in long d4,
                            in long d5);
};
