/* -*- mode: IDL; c-basic-offset: 4; indent-tabs-mode: nil; -*- */
#include "nsISupports.idl"
#include "compzillaIWindow.idl"
#include "nsIDOMWindow.idl"
#include "nsIPropertyBag2.idl"

[scriptable, uuid(38054e08-223b-4eea-adcf-442c58945704)]
interface compzillaIWindowManager : nsISupports
{
  void WindowCreated (in compzillaIWindow window,
                      in long xid, in boolean override,
                      in long x,
                      in long y,
                      in long width,
                      in long height,
                      in boolean mapped);
  void WindowDestroyed (in nsISupports win);

  void WindowMapped (in nsISupports win);
  void WindowUnmapped (in nsISupports win);

  void WindowConfigured (in nsISupports win, 
                         in long x, 
                         in long y, 
                         in long width, 
                         in long height, 
                         in long border,
                         in nsISupports above);

  void PropertyChanged (in nsISupports win, in long atom, in nsIPropertyBag2 bag);

  void SetDocument (in nsISupports doc);
};
